#!/usr/bin/env node
/**
 * Register project-local skills from .agents/skills/ to ~/.agents/skills/
 * and refresh both Claude Code and OpenCode registration.
 * Auto-generated by flow-install. Do not edit manually.
 */
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";

const GLOBAL_SKILLS_DIR = path.join(os.homedir(), ".agents", "skills");
const GLOBAL_COMMANDS_DIR = (process.env.XDG_BIN_HOME || "").trim() || path.join(os.homedir(), ".local", "bin");
const GLOBAL_CLAUDE_MARKETPLACE = path.join(os.homedir(), ".agents", "claude-marketplace");
const GLOBAL_CLAUDE_SETTINGS = path.join(os.homedir(), ".claude", "settings.json");
const GLOBAL_OPENCODE_CONFIG = path.join(os.homedir(), ".config", "opencode", "opencode.json");
const projectRoot = process.cwd();
const projectSkillsRoot = path.join(projectRoot, ".agents", "skills");
const RESERVED_SCRIPT_NAMES = new Set(["register-skills.mjs", "validate-skills.mjs", "register-claude-skills.mjs", "verify-harness.mjs", "sync-rules.mjs", "skills-root.mjs", "skills-root.config.json", "parse-frontmatter.mjs"]);

const pathExists = async (p) => { try { await fs.access(p); return true; } catch { return false; } };
const readFileSafe = async (p) => { try { return await fs.readFile(p, "utf8"); } catch (e) { if (e.code === "ENOENT") return null; throw e; } };
const readJsonSafe = async (p) => { const raw = await readFileSafe(p); if (!raw) return null; try { return JSON.parse(raw); } catch { return null; } };
const copyDir = async (src, dest) => {
  await fs.mkdir(dest, { recursive: true });
  for (const entry of await fs.readdir(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name), d = path.join(dest, entry.name);
    entry.isDirectory() ? await copyDir(s, d) : await fs.copyFile(s, d);
  }
};
const writeJson = async (p, data) => {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, JSON.stringify(data, null, 2) + "\n", "utf8");
};
const parseSimpleYaml = (content) => {
  const data = {};
  if (!content) return data;
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf(":");
    if (idx === -1) continue;
    let value = trimmed.slice(idx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    data[trimmed.slice(0, idx).trim()] = value;
  }
  return data;
};
const parseFrontmatter = (content) => {
  if (!content || !content.startsWith("---")) return null;
  const endIdx = content.indexOf("\n---", 3);
  if (endIdx === -1) return null;
  return { data: parseSimpleYaml(content.slice(4, endIdx)), body: content.slice(endIdx + 4).trim() };
};
const installSkillExecutables = async (skillDir) => {
  const scriptsDir = path.join(skillDir, "scripts");
  if (!(await pathExists(scriptsDir))) return 0;
  await fs.mkdir(GLOBAL_COMMANDS_DIR, { recursive: true });
  let installed = 0;
  const entries = await fs.readdir(scriptsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (entry.name.endsWith(".md")) continue;
    if (path.extname(entry.name) !== "") continue;
    if (RESERVED_SCRIPT_NAMES.has(entry.name)) {
      console.log("  WARN skipping command shim " + entry.name + "; reserved by Flow lifecycle scripts");
      continue;
    }
    const sourcePath = path.join(scriptsDir, entry.name);
    const targetPath = path.join(GLOBAL_COMMANDS_DIR, entry.name);
    try {
      const existingStats = await fs.lstat(targetPath);
      if (existingStats.isSymbolicLink()) {
        const existingTarget = await fs.readlink(targetPath);
        const resolvedExisting = path.resolve(path.dirname(targetPath), existingTarget);
        if (resolvedExisting === sourcePath) {
          installed += 1;
          continue;
        }
      }
      console.log("  WARN skipping command shim " + entry.name + "; " + GLOBAL_COMMANDS_DIR + "/" + entry.name + " already exists");
      continue;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    await fs.chmod(sourcePath, 0o755).catch(() => {});
    await fs.symlink(sourcePath, targetPath);
    console.log("  OK linked command shim " + entry.name);
    installed += 1;
  }
  return installed;
};

const registerClaude = async () => {
  const entries = await fs.readdir(GLOBAL_SKILLS_DIR, { withFileTypes: true }).catch(() => []);
  const skills = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillDir = path.join(GLOBAL_SKILLS_DIR, entry.name);
    const skillMd = await readFileSafe(path.join(skillDir, "SKILL.md"));
    if (!skillMd) continue;
    const frontmatter = parseFrontmatter(skillMd);
    const description = frontmatter?.data?.description || "";
    if (!description) continue;
    const body = frontmatter?.body || skillMd;
    skills.push({ name: entry.name, description, skillDir, body });
  }

  for (const skill of skills) {
    const pluginDir = path.join(skill.skillDir, ".claude-plugin");
    await fs.mkdir(pluginDir, { recursive: true });
    await writeJson(path.join(pluginDir, "plugin.json"), {
      name: skill.name,
      version: "1.0.0",
      description: skill.description,
    });

    const commandsDir = path.join(skill.skillDir, "commands");
    if (!(await pathExists(commandsDir))) {
      await fs.mkdir(commandsDir, { recursive: true });
      await fs.writeFile(
        path.join(commandsDir, skill.name + ".md"),
        "---\ndescription: " + skill.description + "\n---\n\n" + skill.body,
        "utf8",
      );
    }
  }

  await fs.mkdir(path.join(GLOBAL_CLAUDE_MARKETPLACE, ".claude-plugin"), { recursive: true });
  await writeJson(path.join(GLOBAL_CLAUDE_MARKETPLACE, ".claude-plugin", "marketplace.json"), {
    name: "flow_network",
    plugins: skills.map((skill) => ({
      name: skill.name,
      description: skill.description.slice(0, 120),
      version: "1.0.0",
      category: "productivity",
      source: "../skills/" + skill.name,
    })),
  });

  const settings = (await readJsonSafe(GLOBAL_CLAUDE_SETTINGS)) || {};
  if (!settings.extraKnownMarketplaces) settings.extraKnownMarketplaces = {};
  settings.extraKnownMarketplaces.flow_network = {
    source: { source: "directory", path: GLOBAL_CLAUDE_MARKETPLACE },
  };
  delete settings.extraKnownMarketplaces.duru_claude_plugins;
  if (!settings.enabledPlugins) settings.enabledPlugins = {};
  for (const skill of skills) settings.enabledPlugins[skill.name + "@flow_network"] = true;
  delete settings.enabledPlugins["flow-skills@flow_network"];
  await writeJson(GLOBAL_CLAUDE_SETTINGS, settings);

  return skills.length;
};

const registerOpenCode = async () => {
  const config = (await readJsonSafe(GLOBAL_OPENCODE_CONFIG)) || { $schema: "https://opencode.ai/config.json" };
  if (!config.skills) config.skills = {};
  if (!Array.isArray(config.skills.paths)) config.skills.paths = [];
  const normalizePath = async (candidate) => {
    try {
      return await fs.realpath(candidate);
    } catch {
      return path.resolve(candidate);
    }
  };
  const normalizedPaths = [];
  for (const existingPath of config.skills.paths) {
    const normalized = await normalizePath(existingPath);
    if (!normalizedPaths.includes(normalized)) normalizedPaths.push(normalized);
  }
  for (const p of [GLOBAL_SKILLS_DIR, projectSkillsRoot]) {
    const normalized = await normalizePath(p);
    if (!normalizedPaths.includes(normalized)) normalizedPaths.push(normalized);
  }
  config.skills.paths = normalizedPaths;
  await writeJson(GLOBAL_OPENCODE_CONFIG, config);
  return normalizedPaths.length;
};

const run = async () => {
  await fs.mkdir(GLOBAL_SKILLS_DIR, { recursive: true });
  let copied = 0;
  let commandShims = 0;

  if (await pathExists(projectSkillsRoot)) {
    const entries = await fs.readdir(projectSkillsRoot, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(projectSkillsRoot, entry.name);
      if (!(await pathExists(path.join(skillDir, "SKILL.md")))) continue;
      const target = path.join(GLOBAL_SKILLS_DIR, entry.name);
      if (await pathExists(target)) await fs.rm(target, { recursive: true });
      await copyDir(skillDir, target);
      commandShims += await installSkillExecutables(target);
      copied += 1;
      console.log("  OK copied " + entry.name);
    }
  } else {
    console.log("No .agents/skills/ found. Skipping local skill copy.");
  }

  const claudeCount = await registerClaude();
  const opencodePathCount = await registerOpenCode();

  console.log("Copied " + copied + " project skill(s) into " + GLOBAL_SKILLS_DIR);
  console.log("Installed " + commandShims + " command shim(s) into " + GLOBAL_COMMANDS_DIR);
  console.log("Claude Code refreshed for " + claudeCount + " skill(s)");
  console.log("OpenCode skills.paths configured (" + opencodePathCount + " path(s))");
};

run().catch((e) => { console.error("Registration failed:", e); process.exitCode = 1; });
