#!/usr/bin/env node
/**
 * Register project-local skills from .agents/skills/ to ~/.agents/skills/
 * and refresh supported agent runtimes.
 * Auto-generated by flow-install. Do not edit manually.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { GLOBAL_SKILLS_DIR, pathExists, readJsonSafe, registerAllAgentSkills } from "./agents.mjs";

const projectRoot = process.cwd();
const GLOBAL_COMMANDS_DIR = (process.env.XDG_BIN_HOME || "").trim() || path.join(process.env.HOME, ".local", "bin");
const RESERVED_SCRIPT_NAMES = new Set([
  "agents.mjs",
  "register-skills.mjs",
  "validate-skills.mjs",
  "register-claude-skills.mjs",
  "register-opencode-skills.mjs",
  "register-codex-skills.mjs",
  "cleanup-stale-plugins.mjs",
  "verify-harness.mjs",
  "sync-rules.mjs",
  "skills-root.mjs",
  "skills-root.config.json",
  "parse-frontmatter.mjs",
]);
const DEFAULT_INSTALL_PATHS = {
  agentsFile: "AGENTS.md",
  contextDir: ".jarvis/context",
  skillsDir: ".agents/skills",
  scriptsDir: "scripts/flow",
};

const resolveInstallPaths = async () => {
  const lockfile = await readJsonSafe(path.join(projectRoot, "harnessy.lock.json"));
  return { ...DEFAULT_INSTALL_PATHS, ...(lockfile?.installPaths || {}) };
};

const copyDir = async (src, dest) => {
  await fs.mkdir(dest, { recursive: true });
  for (const entry of await fs.readdir(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) await copyDir(s, d);
    else await fs.copyFile(s, d);
  }
};

const installSkillExecutables = async (skillDir) => {
  const scriptsDir = path.join(skillDir, "scripts");
  if (!(await pathExists(scriptsDir))) return 0;
  await fs.mkdir(GLOBAL_COMMANDS_DIR, { recursive: true });
  let installed = 0;
  const entries = await fs.readdir(scriptsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (entry.name.endsWith(".md")) continue;
    if (path.extname(entry.name) !== "") continue;
    if (RESERVED_SCRIPT_NAMES.has(entry.name)) {
      console.log("  WARN skipping command shim " + entry.name + "; reserved by Harnessy lifecycle scripts");
      continue;
    }
    const sourcePath = path.join(scriptsDir, entry.name);
    const targetPath = path.join(GLOBAL_COMMANDS_DIR, entry.name);
    try {
      const existingStats = await fs.lstat(targetPath);
      if (existingStats.isSymbolicLink()) {
        const existingTarget = await fs.readlink(targetPath);
        const resolvedExisting = path.resolve(path.dirname(targetPath), existingTarget);
        if (resolvedExisting === sourcePath) {
          installed += 1;
          continue;
        }
      }
      console.log("  WARN skipping command shim " + entry.name + "; " + GLOBAL_COMMANDS_DIR + "/" + entry.name + " already exists");
      continue;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    await fs.chmod(sourcePath, 0o755).catch(() => {});
    await fs.symlink(sourcePath, targetPath);
    console.log("  OK linked command shim " + entry.name);
    installed += 1;
  }
  return installed;
};

const run = async () => {
  const installPaths = await resolveInstallPaths();
  const projectSkillsRoot = path.resolve(projectRoot, installPaths.skillsDir);
  await fs.mkdir(GLOBAL_SKILLS_DIR, { recursive: true });
  let copied = 0;
  let commandShims = 0;

  if (await pathExists(projectSkillsRoot)) {
    const entries = await fs.readdir(projectSkillsRoot, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(projectSkillsRoot, entry.name);
      if (!(await pathExists(path.join(skillDir, "SKILL.md")))) continue;
      const target = path.join(GLOBAL_SKILLS_DIR, entry.name);
      if (await pathExists(target)) await fs.rm(target, { recursive: true, force: true });
      await copyDir(skillDir, target);
      commandShims += await installSkillExecutables(target);
      copied += 1;
      console.log("  OK copied " + entry.name);
    }
  } else {
    console.log("No project-local skills found at " + projectSkillsRoot + ". Skipping local skill copy.");
  }

  const results = await registerAllAgentSkills(GLOBAL_SKILLS_DIR);

  console.log("Copied " + copied + " project skill(s) into " + GLOBAL_SKILLS_DIR);
  console.log("Installed " + commandShims + " command shim(s) into " + GLOBAL_COMMANDS_DIR);
  console.log("Claude Code refreshed for " + results.claudeCount + " skill(s)");
  console.log("OpenCode skills.paths configured (" + results.opencodePathCount + " path(s))");
  console.log("Codex refreshed for " + results.codexCount + " skill(s)");
};

run().catch((e) => {
  console.error("Registration failed:", e);
  process.exitCode = 1;
});
