"""Output formatters for wiki Q&A answers.

Three formats supported:
- markdown: pass-through for terminal display
- marp_slides: Marp slide deck format
- mermaid: extract or generate a Mermaid diagram
"""

from __future__ import annotations

import re


def format_markdown(answer: str) -> str:
    """Pass-through for terminal display via rich.Markdown."""
    return answer


def format_marp_slides(question: str, answer: str, sources: list[str]) -> str:
    """Convert answer to Marp slide deck format.

    Splits answer on level-2 headers, creating one slide per section.
    The first slide is a title slide with the question.
    The last slide lists sources.

    Args:
        question: Original question (used as title slide text).
        answer: Markdown answer body.
        sources: List of source slugs used in the answer.

    Returns:
        String with Marp frontmatter and slides separated by ---.
    """
    header = "\n".join(
        [
            "---",
            "marp: true",
            "paginate: true",
            "theme: default",
            "---",
            "",
        ]
    )

    title_slide = f"# {question}\n\n*Generated by Jarvis Wiki*"

    # Split answer into sections on level-2 headers
    sections = re.split(r"\n(?=## )", answer.strip())
    slide_bodies = [s.strip() for s in sections if s.strip()]

    slides: list[str] = [title_slide] + slide_bodies

    if sources:
        sources_text = "\n".join(f"- `{s}`" for s in sources)
        slides.append(f"## Sources\n\n{sources_text}")

    return header + "\n\n---\n\n".join(slides) + "\n"


def format_mermaid(answer: str) -> str:
    """Extract or generate a Mermaid diagram from the answer.

    If the answer contains a ```mermaid code block, extracts the first one.
    Otherwise generates a simple mindmap from the answer's bullet points
    or top-level headers.

    Args:
        answer: Markdown answer body.

    Returns:
        String containing a Mermaid code block (```mermaid ... ```).
    """
    # Try to extract an existing mermaid block
    mermaid_match = re.search(r"```mermaid\n(.*?)```", answer, re.DOTALL)
    if mermaid_match:
        return f"```mermaid\n{mermaid_match.group(1).rstrip()}\n```"

    # Generate a mindmap from headers and bullets
    lines = answer.splitlines()
    mindmap_nodes: list[str] = []

    root_text = "Answer"
    for line in lines:
        h2 = re.match(r"^## (.+)", line)
        if h2:
            root_text = h2.group(1).strip()
            break

    for line in lines:
        h2 = re.match(r"^## (.+)", line)
        if h2:
            mindmap_nodes.append(f"    {h2.group(1).strip()}")
            continue
        bullet = re.match(r"^[-*]\s+(.+)", line)
        if bullet:
            text = bullet.group(1).strip()[:80]
            mindmap_nodes.append(f"      {text}")

    if not mindmap_nodes:
        # Fallback: pull first sentence
        first_sentence = re.split(r"[.!?]", answer.strip())[0][:120]
        mindmap_nodes.append(f"    {first_sentence.strip()}")

    inner = "\n".join(mindmap_nodes[:12])  # cap at 12 nodes
    diagram = f"mindmap\n  root(({root_text}))\n{inner}"
    return f"```mermaid\n{diagram}\n```"
