#!/usr/bin/env node

/**
 * flow-install — memory system (Phase 1)
 *
 * Auto-detects project scope hierarchy and generates:
 * - .jarvis/context/scopes/_scopes.yaml
 * - Scoped memory directories with facts/decisions/preferences/events files
 */

import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathExists, readFileSafe, writeIfMissing, ensureDir, log } from "./utils.mjs";

// ---------------------------------------------------------------------------
// Memory file types
// ---------------------------------------------------------------------------

const MEMORY_TYPES = ["facts", "decisions", "preferences", "events"];

const memoryFileContent = (type, scopeLabel) =>
  `# ${type.charAt(0).toUpperCase() + type.slice(1)}

> Scoped to: ${scopeLabel}
> Memory type: ${type}
> One entry per \`---\` block with YAML frontmatter (created_at, status, source)

`;

// ---------------------------------------------------------------------------
// Generate _scopes.yaml from detected project info
// ---------------------------------------------------------------------------

export const generateScopesYaml = (projectInfo) => {
  const orgId = projectInfo.gitOrg || projectInfo.name;
  const projectId = projectInfo.name;

  const scopes = [];

  // Org scope
  scopes.push({
    id: `org:${orgId}`,
    type: "org",
    parent: null,
    path: "scopes/org/",
  });

  // Project scope
  scopes.push({
    id: `project:${projectId}`,
    type: "project",
    parent: `org:${orgId}`,
    path: "scopes/project/",
    match: "**",
  });

  // App scopes (from detected workspaces)
  for (const app of projectInfo.apps) {
    scopes.push({
      id: `app:${app.dirName}`,
      type: "app",
      parent: `project:${projectId}`,
      path: `scopes/project/apps/${app.dirName}/`,
      match: `${app.relativePath}/**`,
    });
  }

  // Build YAML string
  const lines = [
    "# Scope registry — auto-generated by flow-install",
    "# Customize as needed. Re-running flow-install merges new scopes.",
    `# Generated: ${new Date().toISOString().slice(0, 10)}`,
    "",
    "version: 1",
    "",
    "user_scope:",
    '  path_template: "../private/{username}/"',
    "",
    "scopes:",
  ];

  for (const scope of scopes) {
    lines.push(`  - id: "${scope.id}"`);
    lines.push(`    type: ${scope.type}`);
    lines.push(`    parent: ${scope.parent ? `"${scope.parent}"` : "null"}`);
    lines.push(`    path: "${scope.path}"`);
    if (scope.match) {
      lines.push(`    match: "${scope.match}"`);
    }
    lines.push("");
  }

  return { yaml: lines.join("\n"), scopes };
};

// ---------------------------------------------------------------------------
// Install memory system
// ---------------------------------------------------------------------------

export const installMemory = async (projectRoot, projectInfo, { dryRun = false, contextDirRel = ".jarvis/context" } = {}) => {
  const contextDir = path.join(projectRoot, contextDirRel);
  const scopesDir = path.join(contextDir, "scopes");

  // Generate scopes
  const { yaml, scopes } = generateScopesYaml(projectInfo);

  // Write or merge _scopes.yaml
  const scopesYamlPath = path.join(scopesDir, "_scopes.yaml");
  if (await pathExists(scopesYamlPath)) {
    // Merge: parse existing, find new scopes, append
    const existing = await readFileSafe(scopesYamlPath);
    const existingIds = extractScopeIds(existing);
    const newScopes = scopes.filter((s) => !existingIds.has(s.id));

    if (newScopes.length === 0) {
      log.skip("_scopes.yaml (all scopes present)");
    } else if (dryRun) {
      log.dryRun(`Would add ${newScopes.length} scopes to _scopes.yaml`);
    } else {
      // Append new scopes to existing file
      const appendLines = ["", "  # Added by flow-install upgrade"];
      for (const scope of newScopes) {
        appendLines.push(`  - id: "${scope.id}"`);
        appendLines.push(`    type: ${scope.type}`);
        appendLines.push(`    parent: ${scope.parent ? `"${scope.parent}"` : "null"}`);
        appendLines.push(`    path: "${scope.path}"`);
        if (scope.match) appendLines.push(`    match: "${scope.match}"`);
        appendLines.push("");
      }
      await fs.appendFile(scopesYamlPath, appendLines.join("\n"), "utf8");
      log.ok(`_scopes.yaml: ${newScopes.length} scopes added`);
    }
  } else {
    // Fresh creation
    if (dryRun) {
      log.dryRun("Would create _scopes.yaml");
    } else {
      await ensureDir(scopesDir);
      await fs.writeFile(scopesYamlPath, yaml, "utf8");
      log.ok("_scopes.yaml created");
    }
  }

  // Create scoped memory directories
  for (const scope of scopes) {
    const scopeDir = path.join(contextDir, scope.path);
    const scopeLabel = scope.id;

    for (const type of MEMORY_TYPES) {
      const filePath = path.join(scopeDir, `${type}.md`);
      if (await pathExists(filePath)) continue;

      if (dryRun) {
        log.dryRun(`Would create ${scope.path}${type}.md`);
      } else {
        await ensureDir(scopeDir);
        await fs.writeFile(filePath, memoryFileContent(type, scopeLabel), "utf8");
      }
    }
  }

  // Create user memory directory
  const username = os.userInfo().username;
  const userDir = path.join(contextDir, "private", username);
  for (const type of MEMORY_TYPES) {
    const filePath = path.join(userDir, `${type}.md`);
    if (await pathExists(filePath)) continue;
    if (dryRun) {
      log.dryRun(`Would create private/${username}/${type}.md`);
    } else {
      await ensureDir(userDir);
      await fs.writeFile(filePath, memoryFileContent(type, `user:${username}`), "utf8");
    }
  }

  if (!dryRun) {
    log.ok(`Memory system installed (${scopes.length} scopes, ${MEMORY_TYPES.length} types each)`);
  }
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const extractScopeIds = (yamlContent) => {
  const ids = new Set();
  if (!yamlContent) return ids;
  const regex = /id:\s*"?([^"\n]+)"?/g;
  let match;
  while ((match = regex.exec(yamlContent))) {
    ids.add(match[1].trim());
  }
  return ids;
};
